apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: existing-mono-inrepo-noport-noingress-autodeploy-20250820143906
build:
  tagPolicy:
    sha256: {}
  platforms: ["linux/amd64", "darwin/arm64"]
  artifacts:
  - image: ghcr.io/existing-mono-inrepo-noport-noingress-autodeploy-20250820143906
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
          - "go.mod"
          - "**/*.go"
manifests:
  kustomize:
    paths:
    - deploy/overlays/dev
profiles:
- name: prod
  manifests:
    kustomize:
      paths:
      - deploy/overlays/prod
